const data = [
  {
    key: '1',
    bride: 'Anna',
    groom: 'Johan',
    phone: '08123456789',
    address: 'New York No. 1 Lake Park',
    wedding_date: '07-05-2021',
    wedding_time: '13.00',
    wedding_place: 'Manggala Wanabakti',
    wedding_address: 'Jl. Gatot Subroto',
    status: 1,
  },
  {
    key: '2',
    bride: 'Anna',
    groom: 'Johan',
    phone: '08123456789',
    address: 'New York No. 1 Lake Park',
    wedding_date: '07-05-2021',
    wedding_time: '13.00',
    wedding_place: 'Manggala Wanabakti',
    wedding_address: 'Jl. Gatot Subroto',
    status: 1,
  },
  {
    key: '3',
    bride: 'Anna',
    groom: 'Johan',
    phone: '08123456789',
    address: 'New York No. 1 Lake Park',
    wedding_date: '07-05-2021',
    wedding_time: '13.00',
    wedding_place: 'Manggala Wanabakti',
    wedding_address: 'Jl. Gatot Subroto',
    status: 1,
  },
  {
    key: '4',
    bride: 'Anna',
    groom: 'Johan',
    phone: '08123456789',
    address: 'New York No. 1 Lake Park',
    wedding_date: '07-05-2021',
    wedding_time: '13.00',
    wedding_place: 'Manggala Wanabakti',
    wedding_address: 'Jl. Gatot Subroto',
    status: 1,
  },
];

export default data